```{r}
library(gstar)
library(xts)
library(tseries)
```

```{r}
#-----import dataset----#
df <- read.csv("dataset.csv", header=TRUE)
df <- df[,c("DateTime","Zone1","Zone2","Zone3")]
```

```{r}
#-----adjust date time format----#
df$DateTime <- as.POSIXct(df$DateTime,format='%m/%d/%Y %H:%M')
df$Date <- strftime(df$DateTime,format='%Y-%m-%d')
df$Time <- strftime(df$DateTime,format='%H:%M')

df <- df[df$Time == "00:00",c("DateTime","Zone1","Zone2","Zone3")]
```

```{r}
ts.plot(df['Zone1'], col='red', xlab='Waktu', ylab='Consumtion', main='Konsumsi Listrik Wilayah 1')

ts.plot(df['Zone2'], col='red', xlab='Waktu', ylab='Consumtion', main='Konsumsi Listrik Wilayah 2')

ts.plot(df['Zone3'], col='red', xlab='Waktu', ylab='Consumtion', main='Konsumsi Listrik Wilayah 3')
```


```{r}
# Zone1
adf.test(as.matrix(df[2]))
```

```{r}
# Zone2
adf.test(as.matrix(df[3]))
```

```{r}
# Zone3
adf.test(as.matrix(df[4]))
```

```{r}
cf1 <- ccf(df[2], df[3], plot=TRUE)

print(cf1)
```

```{r}
cf2 <- ccf(df[3], df[4], plot=TRUE)

print(cf2)
```

```{r}
cf3 <- ccf(df[2], df[4], plot=TRUE)

print(cf3)
```

```{r}
#-----Use data with xts object----#
x = xts(df[, -1], order.by = df$DateTime)
s <- round(nrow(x) * 0.8) # 0.8
```

```{r}
## split into training and testing (80:20)
x_train <- x[1:s, ]
x_test <- x[-c(1:s), ]
```

```{r}
weight = matrix(c(0, 1, 1, # create the uniform weight.
                  1, 0, 1,
                 1, 1, 0), ncol = 3, nrow = 3)
weight = weight/(ncol(x) - 1) #the sum of weight is equal to 1 every row.
weight
```


```{r}
#hasil param
zone1_1 <- df[-1,2]
zone2_1 <- df[-1,3]
zone3_1 <- df[-1,4]

zone1_364 <- df[-364,2]
zone2_364 <- df[-364,3]
zone3_364 <- df[-364,4]

b1_zone1 <- 0.5*(zone2_364+zone3_364)
b1_zone2 <- 0.5*(zone1_364+zone3_364)
b1_zone3 <- 0.5*(zone1_364+zone2_364)

#NOL
NOL_364 <- rep(0, 363)


X <- matrix(c(zone1_364, NOL_364, NOL_364, NOL_364, zone2_364, NOL_364,NOL_364, NOL_364, zone3_364,
              b1_zone1, NOL_364,NOL_364,NOL_364, b1_zone2, NOL_364, NOL_364, NOL_364, b1_zone3), ncol=6)

mtrx <- t(X)%*%X
inv_mtrx <- solve(mtrx)


#MATRIX Y
Y <- matrix(c(zone1_1, zone2_1, zone3_1), ncol = 1)
parm <- inv_mtrx%*%t(X)%*%Y
parm

#r12 <- 0.94921371
#r13 <- 0.97314842
# <- 0.98399176
r12 <- parm[1,1]
r13 <- parm[2,1]
r23 <- parm[3,1]

W <- matrix(c(0,r12/(r12+r13), r13/(r12+r13),
              r12/(r12+r13), 0, r23/(r12+r23),
              r13/(r13+r12), r23/(r12+r23),0),3,3)
W

```

```{r}
fit <- gstar(x_train, weight = weight, p = 1, d = 0, est = "OLS")
fit
summary(fit)
```

```{r}
performance(fit)
```

```{r}
performance(fit, x_test) ## to check the performance with testing data
```

```{r}
predict(fit, n = 10) #forecast 10 data ahead
```

```{r}
plot(fit)
```

```{r}
plot(fit, n_predict = 10) #plot with 10 forecasting data
```

```{r}
plot(fit, testing = x_test)
```
